## Numpy Array Operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print ("Basic Slicing", arr[2:7])
print ("With step", arr[1:8:2])
print ("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative Indexing 8


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:,1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


## Sorting

In [4]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filters

In [3]:
number = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = number [number % 2 == 0 ]
print ("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [ ]:
mask = number > 5
print ("Numbers greater than 5", number[mask])


Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [ ]:
indices = [0,2,4]
print (number[indices])

where_result = np.where(number > 5)
print (where_result)
print ("NP where", number [where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [6]:
condition_array = np.where(number > 5, number*2, number)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## adding and removing data  

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate ((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## array compatiblity

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility Shapes", a.shape == b.shape)

Compatibility Shapes False


In [12]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack ((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [15]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)
print("Array after deletion:", deleted)

Array after deletion: [1 2 4 5 6]
