## Numpy array and basics

In [8]:
import numpy as np

### Creating array from list

In [5]:
arr_1d = np.array([1,2,3,4,5])
print ("1D array: ", arr_1d)
arr_2d = np.array([[1,2,3], [4,5,6]])
print ("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


###List Vs Numpy    

In [11]:
py_list = [1,2,3]
print ("python list multiplacation", py_list * 2 )

np_array = np.array ([1,2,3,4])
print ("python array multiplacation", np_array * 2 )

import time
start = time.time()
py_list =[i*2 for i in range (1000000)]
print ("\n List operation time: ", time.time()- start)

start =time.time()
np_array = np.arange(1000000) * 2
print ("\n Numpy operation time: ", time.time ()- start)

python list multiplacation [1, 2, 3, 1, 2, 3]
python array multiplacation [2 4 6 8]

 List operation time:  0.15096092224121094

 Numpy operation time:  0.007954120635986328


### Creating array from scratch

In [19]:
zeros = np.zeros((3,4))
print ("zeros array: \n", zeros)

ones = np.ones ((3,4))
print ("one array: \n", ones)

full = np.full ((2,2),7)
print ("full array: \n", full)

random = np.random.random((2,3))
print ("random array: \n", random)

sequence = np.arange(0, 10, 2)
print ("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.23229008 0.66950059 0.18643675]
 [0.14741752 0.67550601 0.01748893]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix & Tensor 

In [25]:
vector = np.array([1,2,3,4])
print("Vector:", vector)

matrix = np.array([[1,2,3],
                   [4,5,6,]])
print("Matrix :", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor :", tensor)

Vector: [1 2 3 4]
Matrix : [[1 2 3]
 [4 5 6]]
Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
print ("Shape ", arr.shape)
print ("Dimension ", arr.ndim)
print ("Size ", arr.size)
print ("DType ", arr.dtype)

